### PR TITLE
adding a scenario coverage document

### PR DESCRIPTION
**Pull request by sauryadas**
They will make it available when we GA on ACOM. I have added as many scenarios as i could discover.

### CODE REVIEW

**Comment by sauryadas** [comment]
@rjtsdl Can you please approve?

**Comment by sauryadas** [comment]
@shrutir25 you can review and approve this. ill merge

**Comment by shrutir25** [comment]
lgtm

**Comment by rjtsdl** [comment]
LGTM, sorry for the late response.

**Pull request merged**
